BOOTLOADER = caterina
LTO_ENABLE = yes  # Makes hex file smaller

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RGBLIGHT_ENABLE = yes

#Disable on all to save space
AUTO_SHIFT_ENABLE = no
BOOTMAGIC_ENABLE = no
CAPS_WORD_ENABLE = no
COMBO_ENABLE = no
COMMAND_ENABLE = no
DEFERRED_EXEC_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_LOCK_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no
MAGIC_ENABLE = no
MIDI_ENABLE = no
MOUSE_ENABLE = no
NKRO_ENABLE = no
OLED_ENABLE = no
RGB_MATRIX_ENABLE = no
SLEEP_LED_ENABLE = no
SPACE_CADET_ENABLE = no
SWAP_HANDS_ENABLE = no
TAP_DANCE_ENABLE = no
TRI_LAYER_ENABLE = no
UCIS_ENABLE = no
UNICODEMAP_ENABLE = no
UNICODE_ENABLE = np
